### ISSUE TITLE
Issue with SQLPlus Script Runner Plugin

### ISSUE THREAD

**Issue by MrinalSam** [jenkinsci/sqlplus-script-runner-plugin#18]
Dear Team,

I have updated custom oracle home , sqlplus location and TNS_ADMIN path ...

Then I am getting below error, it is unable to find the Oracle Home path though it is provided... While earlier version was running smoothly...

PFB the error details...

========================================================

-------------------------------------------------------------------------- Getting ORACLE_HOME... Using custom SQL*Plus location SQL*Plus >>> /dboracle/orabase/product/10.2.0/bin/sqlplus Using custom TNS_ADMIN location TNS_ADMIN >>> /dboracle/orabase/product/10.2.0/network/admin [DEBUG] Using custom ORACLE_HOME -------------------------------------------------------------------------- Using custom ORACLE_HOME  detected host = cbl06698dat02  slave machine ? false -------------------------------------------------------------------------- Using ORACLE_HOME =/dboracle/orabase/product/10.2.0 -------------------------------------------------------------------------- Getting SQLPlus version [DEBUG] ORACLE_HOME = /dboracle/orabase/product/10.2.0 [DEBUG] LD_LIBRARY_PATH = /dboracle/orabase/product/10.2.0/lib SQL*Plus exec file = sqlplus -------------------------------------------------------------------------- [DEBUG] Statement: /dboracle/orabase/product/10.2.0/bin/sqlplus -v  -------------------------------------------------------------------------- [Orbit] $ /dboracle/orabase/product/10.2.0/bin/sqlplus -v Error 6 initializing SQL*Plus Message file sp1<lang>.msb not found SP2-0750: You may need to set ORACLE_HOME to your Oracle software directory Process exited with status 1 --------------------------------------------------------------------------  detected host = cbl06698dat02 -------------------------------------------------------------------------- Using ORACLE_HOME =/dboracle/orabase/product/10.2.0 -------------------------------------------------------------------------- Running defined script on silbxx/********@orbdw_any_scan Temp script: file:/orbit_serial/jenkins/home/workspace/Orbit/temp-script-15180746804457289186717442500254.sql -------------------------------------------------------------------------- [DEBUG] ORACLE_HOME = /dboracle/orabase/product/10.2.0 [DEBUG] LD_LIBRARY_PATH = /dboracle/orabase/product/10.2.0/lib:/dboracle/orabase/product/10.2.0 Work Directory = /orbit_serial/jenkins/home/workspace/Orbit [DEBUG]  Statement: -------------------------------------------------------------------------- /dboracle/orabase/product/10.2.0/bin/sqlplus -L silbxx/Jas0N_B0u4n3@orbdw_any_scan @/orbit_serial/jenkins/home/workspace/Orbit/temp-script-15180746804457289186717442500254.sql --------------------------------------------------------------------------   [Orbit] $ /dboracle/orabase/product/10.2.0/bin/sqlplus -L silbxx/Jas0N_B0u4n3@orbdw_any_scan @/orbit_serial/jenkins/home/workspace/Orbit/temp-script-15180746804457289186717442500254.sql Error 6 initializing SQL*Plus Message file sp1<lang>.msb not found SP2-0750: You may need to set ORACLE_HOME to your Oracle software directory Process exited with status 1 -------------------------------------------------------------------------- Exit code: 1 -------------------------------------------------------------------------- java.lang.RuntimeException: Process exited with error  at org.jenkinsci.plugins.sqlplusscriptrunner.SQLPlusRunner.run(SQLPlusRunner.java:385)  at org.jenkinsci.plugins.sqlplusscriptrunner.SQLPlusRunnerBuilder.perform(SQLPlusRunnerBuilder.java:112)  at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)  at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)  at hudson.model.Build$BuildExecution.build(Build.java:206)  at hudson.model.Build$BuildExecution.doRun(Build.java:163)  at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)  at hudson.model.Run.execute(Run.java:1727)  at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)  at hudson.model.ResourceController.execute(ResourceController.java:97)  at hudson.model.Executor.run(Executor.java:429) ERROR: Process exited with error SSH: Current build result is [FAILURE], not going to run. Finished: FAILURE

==================================================================

Please can you guide what details needs to be updated in this latest plugin and where it would be.

Thanks,

Mrinal

**Comment by mlflr** [comment]
Hi,
Same issue here after upgrading to 1.0.11, works fine after reverting back to 1.0.10. It seems ORACLE_HOME environment variable is not configured properly before executing sqlplus -v.

Jenkins 2.89.4 (LTS branch) on RHEL7, running on master.

**Comment by boaglio** [comment]
Please try to follow these steps: 

1.  Define ORACLE_HOME inside .bashrc file from the same user you run Jenkins;
2.     Reboot your machine;
3.     Use option  Try to detect ORACLE_HOME from Jenkins general configuration;
4.     Remove any custom configuration from you job;
5.     Try to run a build again.

**Comment by MrinalSam** [comment]
Many Thanks Boagilo,

This solution is working , now we are able to connect oracle database from Jenkins..

 

But Unfortunately Jenkins is not transferring/executing  the actual scipt (which I am trying to execute ) .sql file ...

Jenkins is converting the .sql file into only one semicolon...

PFB actual script and transferred one...

Actual .sql file : (test.sql)

select sysdate from dual ;
show user ;

Jenkin's Transferred/Executed:

prod@cbl06698dat02>pwd

/orbit_serial/jenkins/home/workspace/Orbit/Code_Base/DB_Scripts/Schema

prod@cbl06698dat02>ls -lrt

total 0 -rw-r----- 1 prod release 8 Mar  8 13:25 test.sql prod@cbl06698dat02>cat test.sql

; exit;

 

prod@cbl06698dat02>


Please can you suggest why this is happening and how we can overcome this to execute right script from Jenkins..

Thanks,
Mrinal Sannyasi

**Comment by rarawal** [comment]
By appending Exit; at end of the script
